# Development overrides for nginx-demo

replicaCount: 1

image:
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    service.beta.kubernetes.io/oci-load-balancer-preserve-source: "true"
    # Optional: set OCI subnet OCIDs if needed
    # service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1..example"
    # service.beta.kubernetes.io/oci-load-balancer-subnet2: "ocid1.subnet.oc1..example"
  externalTrafficPolicy: Local
  loadBalancerSourceRanges: []

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: dev.example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

podAnnotations:
  environment: dev
