{{- if .Values.application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  project: {{ .Values.application.project }}
  source:
    repoURL: {{ .Values.application.source.repoURL | quote }}
    targetRevision: {{ .Values.application.source.targetRevision | quote }}
    path: {{ .Values.application.source.path | quote }}
    {{- with .Values.application.source.helm }}
    helm:
      {{- with .valueFiles }}
      valueFiles:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .parameters }}
      parameters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .Values.application.destination.server | quote }}
    namespace: {{ .Values.application.destination.namespace | quote }}
  {{- with .Values.application.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

